config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about'

  devise_for :players,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

namespace :admin do
    resources :players
    resources :quizzes
    resources :request_quizzes
  end
  patch "quiz/:id/score_update" => "user/players#score_update", as: "score_update"

namespace :user do
    resources :players
    resources :quizzes
    resources :request_quizzes
  end

  post 'homes/about', to: 'homes#about', as: 'confirm'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image_icon
end

app/models/quiz.rb
class Quiz < ApplicationRecord
end

app/models/request_quiz.rb
class RequestQuiz < ApplicationRecord
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < ApplicationController
  def index
    @players = Player.page(params[:page]).per(10)
  end
end

app/controllers/admin/quizzes_controller.rb
class Admin::QuizzesController < ApplicationController
  def new
    @quiz = Quiz.new
  end

  def index
    @quizzes = Quiz.page(params[:page]).per(10)
  end

  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.save
    redirect_to admin_quizzes_path
  end

  def edit
    @quiz = Quiz.find(params[:id])
  end

  def update
    @quiz = Quiz.find(params[:id])
    @quiz.update(quiz_params)
    flash[:notice] = "変更しました"
    redirect_to admin_quizzes_path
  end

  private
  def quiz_params
    params.require(:quiz).permit(:question, :answer, :choices_first, :choices_second, :choices_third, :choices_fourth, :explanation)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected
  def after_sign_in_path_for(resource)
    admin_request_quizzes_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:player_name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/players_controller.rb
class User::PlayersController < ApplicationController
  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    @player.update(player_params)
    redirect_to request.referer
  end

  def score_update
    @quiz = Quiz.find(params[:id])
    answer = params[:answer]
    if @quiz.answer == answer
      current_player.update(score: current_player.score + 1)
    end
  end

  def index
    @player_ranks = Player.all.order(score: :desc).limit(5)
  end

  private
  def player_params
    params.require(:player).permit(:player_name, :email, :introduction,:image_icon)
  end
end

app/controllers/user/quizzes_controller.rb
class User::QuizzesController < ApplicationController
  before_action :authenticate_player!
  def index
     quiz_all_list = Quiz.all.pluck(:id) # quiz_all_list = ["1","2","3"...]
    if params[:count]
      # 2問~10問
      quiz_list = quiz_all_list - params[:used_quizzes].split(",").map(&:to_i)
      # quiz_all_list - params[:used_quizzes]　回答した問題をquiz_all_list配列から引いていく

      @quiz = Quiz.find(quiz_list.shuffle[0])
      # すでに答えた問題を抜いた配列の中からランダムで出題

      @count = params[:count].to_i + 1
      @used_quizzes = params[:used_quizzes].split(",").push(@quiz.id).join(",")
      # split(",") 配列にし、出題した問題を配列にいれ、表示するためにjoinを使用
    else
      #1問目
      @count = 1
      @quiz = Quiz.find(quiz_all_list.shuffle[0])
      @used_quizzes = @quiz.id
      current_player.update(score: 0)
    end
  end

  def new
    @player = current_player
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/players_helper.rb
module Admin::PlayersHelper
end

app/helpers/admin/quizzes_helper.rb
module Admin::QuizzesHelper
end

app/helpers/admin/request_quizzes_helper.rb
module Admin::RequestQuizzesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user/players_helper.rb
module User::PlayersHelper
end

app/helpers/user/quizzes_helper.rb
module User::QuizzesHelper
end

app/helpers/user/request_quizzes_helper.rb
module User::RequestQuizzesHelper
end

app/views/admin/quizzes/edit.html.erb
<div class="admin-login-top">
  <h3>クイズ内容を変更することができます</h3>

  <%= form_with model: @quiz,url: admin_quiz_path(@quiz.id), method: :patch, local: true do |f| %>
    <div class="quiz-check">
      <dl>
        <dt><%= f.label :'問題' %></dt> <dd><%= f.text_area :question, :size=>"100x5" %></dd>
        <dt><%= f.label :'答え' %></dt> <dd><%= f.text_field :answer, :size=>"20" %></dd>
        <dt><%= f.label :'選択肢ア' %></dt> <dd><%= f.text_area :choices_first, :size=>"100x2" %></dd>
        <dt><%= f.label :'選択肢イ' %></dt> <dd><%= f.text_area :choices_second, :size=>"100x2" %></dd>
        <dt><%= f.label :'選択肢ウ' %></dt> <dd><%= f.text_area :choices_third, :size=>"100x2" %></dd>
        <dt><%= f.label :'選択肢エ' %></dt> <dd><%= f.text_area :choices_fourth, :size=>"100x2" %></dd>
        <dt><%= f.label :'解説' %></dt> <dd><%= f.text_area :explanation, :size=>"100x5" %></dd>
      </dl>
    </div>
    <%= f.submit '変更を保存', class: 'quiz-new-button' %>
  <% end %>
</div>

app/views/admin/quizzes/index.html.erb
<div class="admin-login-top">
  <h3 class="admin-login-space">現在出題しているクイズの一覧を確認することができます</h3>

  <div class="quiz-index">
    <% @quizzes.each do |quiz|%>
      <div class="quiz-index-adjustment">
        <%= quiz.id %>
        <%= link_to quiz.question.truncate(47, omission: '...'),edit_admin_quiz_path(quiz.id) %>
      </div>
   <% end %>
  </div>
  <%= paginate @quizzes %>
</div>

app/views/admin/quizzes/new.html.erb
<div class="admin-login-top">
  <h3>クイズを新しく作成できます。<br>ユーザーが作成したクイズもこちらから作成してください。</h3>

  <%= form_with model: @quiz,url: admin_quizzes_path,method: :post, local: true do |f| %>
    <div class="quiz-check">
      <dl>
        <dt><%= f.label :'問題' %></dt> <dd><%= f.text_area :question, :size=>"100x5" %></dd>
        <dt><%= f.label :'答え' %></dt> <dd><%= f.select :answer, options_for_select([["ア", "ア"], ["イ", "イ"], ["ウ", "ウ"], ["エ", "エ"]]), options = { include_blank: true } %></dd>
        <dt><%= f.label :'選択肢ア' %></dt> <dd><%= f.text_area :choices_first, :size=>"50x2" %></dd>
        <dt><%= f.label :'選択肢イ' %></dt> <dd><%= f.text_area :choices_second, :size=>"50x2" %></dd>
        <dt><%= f.label :'選択肢ウ' %></dt> <dd><%= f.text_area :choices_third, :size=>"50x2" %></dd>
        <dt><%= f.label :'選択肢エ' %></dt> <dd><%= f.text_area :choices_fourth, :size=>"50x2" %></dd>
        <dt><%= f.label :'解説' %></dt> <dd><%= f.text_area :explanation, :size=>"100x5" %></dd>
      </dl>
    <div>
    <%= f.submit '作成', class: 'quiz-new-button' %>
  <% end %>
<div>