config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about'

  devise_for :players,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

namespace :admin do
    resources :players
    resources :quizzes
    resources :request_quizzes
  end
  patch "quiz/:id/score_update" => "user/players#score_update", as: "score_update"

namespace :user do
    resources :players
    resources :quizzes
    resources :request_quizzes
  end

  post 'homes/about', to: 'homes#about', as: 'confirm'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/quizzes_controller.rb
class Admin::QuizzesController < ApplicationController
  def new
    @quiz = Quiz.new
  end

  def index
    @quizzes = Quiz.page(params[:page]).per(10)
  end

  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.save
    redirect_to admin_quizzes_path
  end

  def edit
    @quiz = Quiz.find(params[:id])
  end

  def update
    @quiz = Quiz.find(params[:id])
    @quiz.update(quiz_params)
    flash[:notice] = "変更しました"
    redirect_to admin_quizzes_path
  end

  private
  def quiz_params
    params.require(:quiz).permit(:question, :answer, :choices_first, :choices_second, :choices_third, :choices_fourth, :explanation)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/players_controller.rb
class User::PlayersController < ApplicationController
  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    @player.update(player_params)
    redirect_to request.referer
  end

  def score_update
    @quiz = Quiz.find(params[:id])
    answer = params[:answer]
    if @quiz.answer == answer
      current_player.update(score: current_player.score + 1)
    end
  end

  def index
    @player_ranks = Player.all.order(score: :desc).limit(5)
  end

  private
  def player_params
    params.require(:player).permit(:player_name, :email, :introduction,:image_icon)
  end
end

app/controllers/user/quizzes_controller.rb
class User::QuizzesController < ApplicationController
  before_action :authenticate_player!
  def index
     quiz_all_list = Quiz.all.pluck(:id) # quiz_all_list = ["1","2","3"...]
    if params[:count]
      # 2問~10問
      quiz_list = quiz_all_list - params[:used_quizzes].split(",").map(&:to_i)
      # quiz_all_list - params[:used_quizzes]　回答した問題をquiz_all_list配列から引いていく

      @quiz = Quiz.find(quiz_list.shuffle[0])
      # すでに答えた問題を抜いた配列の中からランダムで出題

      @count = params[:count].to_i + 1
      @used_quizzes = params[:used_quizzes].split(",").push(@quiz.id).join(",")
      # split(",") 配列にし、出題した問題を配列にいれ、表示するためにjoinを使用
    else
      #1問目
      @count = 1
      @quiz = Quiz.find(quiz_all_list.shuffle[0])
      @used_quizzes = @quiz.id
      current_player.update(score: 0)
    end
  end

  def new
    @player = current_player
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/request_quizzes_controller.rb
class User::RequestQuizzesController < ApplicationController
  def new
    @request_quiz = RequestQuiz.new
  end

  def create
    @request_quiz = RequestQuiz.new(request_quiz_params)
    @request_quiz.save
    redirect_to user_request_quizzes_path
  end

  private
  def request_quiz_params
    params.require(:request_quiz).permit(:question, :answer, :choices_first, :choices_second, :choices_third, :choices_fourth, :explanation)
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/quizzes_helper.rb
module Admin::QuizzesHelper
end

app/helpers/user/players_helper.rb
module User::PlayersHelper
end

app/helpers/user/quizzes_helper.rb
module User::QuizzesHelper
end

app/helpers/user/request_quizzes_helper.rb
module User::RequestQuizzesHelper
end

app/views/user/quizzes/index.html.erb
<% if @count == 10 %>
  <div>
    <h2 class="faq">第 <%= @count %> 問</h2>
    <h3 class="question"><%= @quiz.question %></h3>
  </div>

  <div class="hidden_box">
    <%= link_to 'ア', score_update_path(@quiz, answer: "ア"), method: :patch, remote: true, class: 'select-button' %>
    <%= @quiz.choices_first %>
  </div>

  <div class="hidden_box">
    <%= link_to 'イ', score_update_path(@quiz, answer: "イ"), method: :patch, remote: true, class: 'select-button' %>
    <%= @quiz.choices_second %>
  </div>

  <div class="hidden_box">
    <%= link_to 'ウ', score_update_path(@quiz, answer: "ウ"), method: :patch, remote: true, class: 'select-button' %>
    <%= @quiz.choices_third %>
  </div>

  <div class="hidden_box">
    <%= link_to 'エ', score_update_path(@quiz, answer: "エ"), method: :patch, remote: true, class: 'select-button' %>
    <%= @quiz.choices_fourth %>

    <div class="answer-explanation"><label for="label1" class="answer-open">答えと解説を見る</label></div>
    <input type="checkbox" id="label1" class="switch" />
      <div class="hidden_show">
        <h3 class="answer-title">正解：<%= @quiz.answer %></h3>
        <div><strong>解説：</strong><%= @quiz.explanation %></div>
        <div class="next-title">
          <h4 class="last-title">問題は以上です。お疲れ様でした！</h4><%= link_to "結果を見る", new_user_quiz_path, class: 'next-button' %></div>
      </div>
  </div>

<% else %>

  <div>
    <h2 class="faq">第 <%= @count %> 問</h2>
    <h3 class="question"><%= @quiz.question %></h3>
  </div>

  <div class="hidden_box">
    <%= link_to 'ア', score_update_path(@quiz, answer: "ア"), method: :patch, remote: true, class: 'select-button' %>
    <%= @quiz.choices_first %>
  </div>

  <div class="hidden_box">
    <%= link_to 'イ', score_update_path(@quiz, answer: "イ"), method: :patch, remote: true, class: 'select-button' %>
    <%= @quiz.choices_second %>
  </div>

  <div class="hidden_box">
    <%= link_to 'ウ', score_update_path(@quiz, answer: "ウ"), method: :patch, remote: true, class: 'select-button' %>
    <%= @quiz.choices_third %>
  </div>

  <div class="hidden_box">
    <%= link_to 'エ', score_update_path(@quiz, answer: "エ"), method: :patch, remote: true, class: 'select-button' %>
    <%= @quiz.choices_fourth %>

    <div class="answer-explanation"><label for="label1" class="answer-open">答え & 解説を見る</label></div>
    <input type="checkbox" id="label1" class="switch" />
      <div class="hidden_show">
        <h3 class="answer-title">正解：<%= @quiz.answer %></h3>
        <div><strong>解説：</strong><%= @quiz.explanation %></div>
        <div class="next-title">
          <%= link_to "次の問題へ", user_quizzes_path(count: @count, quiz: @quiz.id, used_quizzes: @used_quizzes), class: 'next-button' %></div>
        </div>
  </div>


<% end %>

app/views/user/quizzes/new.html.erb
<h4 class="result">あなたの合計点数は...</h4>
<h1 class="player-score"><%= @player.score %></h1>

<% if @player.score != 10 %>
  <div class="result">
    <h3>お疲れ様でした！<br>
    全問正解しますと、あなただけのオリジナルのクイズを作成することができます。<br>
    またの挑戦をお待ちしております！</h3>
  </div>
  <div class="next-title"><%= link_to 'トップページへ戻る' ,root_path, class: 'next-button' %></div>
<% end %>

<% if @player.score == 10 %>
  <div class="result">
    <h3>満点です！おめでとう！<br>全問正解でしたので、あなただけのオリジナルのクイズを作成することができます</h3>
    <div class="next-title"><%= link_to "クイズを作成する", new_user_request_quiz_path, class: 'next-button' %></div>
  </div>
<% end %>