config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about'

  devise_for :players,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

namespace :admin do
    resources :players
    resources :quizzes
    resources :request_quizzes
  end
  patch "quiz/:id/score_update" => "user/players#score_update", as: "score_update"

namespace :user do
    resources :players
    resources :quizzes
    resources :request_quizzes
  end

  post 'homes/about', to: 'homes#about', as: 'confirm'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image_icon
end

app/models/quiz.rb
class Quiz < ApplicationRecord
end

app/models/request_quiz.rb
class RequestQuiz < ApplicationRecord
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < ApplicationController
  def index
    @players = Player.page(params[:page]).per(10)
  end
end

app/controllers/admin/quizzes_controller.rb
class Admin::QuizzesController < ApplicationController
  def new
    @quiz = Quiz.new
  end

  def index
    @quizzes = Quiz.page(params[:page]).per(10)
  end

  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.save
    redirect_to admin_quizzes_path
  end

  def edit
    @quiz = Quiz.find(params[:id])
  end

  def update
    @quiz = Quiz.find(params[:id])
    @quiz.update(quiz_params)
    flash[:notice] = "変更しました"
    redirect_to admin_quizzes_path
  end

  private
  def quiz_params
    params.require(:quiz).permit(:question, :answer, :choices_first, :choices_second, :choices_third, :choices_fourth, :explanation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:player_name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/players_controller.rb
class User::PlayersController < ApplicationController
  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    @player.update(player_params)
    redirect_to request.referer
  end

  def score_update
    @quiz = Quiz.find(params[:id])
    answer = params[:answer]
    if @quiz.answer == answer
      current_player.update(score: current_player.score + 1)
    end
  end

  def index
    @player_ranks = Player.all.order(score: :desc).limit(5)
  end

  private
  def player_params
    params.require(:player).permit(:player_name, :email, :introduction,:image_icon)
  end
end

app/controllers/user/quizzes_controller.rb
class User::QuizzesController < ApplicationController
  before_action :authenticate_player!
  def index
     quiz_all_list = Quiz.all.pluck(:id) # quiz_all_list = ["1","2","3"...]
    if params[:count]
      # 2問~10問
      quiz_list = quiz_all_list - params[:used_quizzes].split(",").map(&:to_i)
      # quiz_all_list - params[:used_quizzes]　回答した問題をquiz_all_list配列から引いていく

      @quiz = Quiz.find(quiz_list.shuffle[0])
      # すでに答えた問題を抜いた配列の中からランダムで出題

      @count = params[:count].to_i + 1
      @used_quizzes = params[:used_quizzes].split(",").push(@quiz.id).join(",")
      # split(",") 配列にし、出題した問題を配列にいれ、表示するためにjoinを使用
    else
      #1問目
      @count = 1
      @quiz = Quiz.find(quiz_all_list.shuffle[0])
      @used_quizzes = @quiz.id
      current_player.update(score: 0)
    end
  end

  def new
    @player = current_player
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/players_helper.rb
module Admin::PlayersHelper
end

app/helpers/admin/quizzes_helper.rb
module Admin::QuizzesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user/players_helper.rb
module User::PlayersHelper
end

app/helpers/user/quizzes_helper.rb
module User::QuizzesHelper
end

app/helpers/user/request_quizzes_helper.rb
module User::RequestQuizzesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudiesIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
       <h1 class="header-logo"><a class="header-link" href="/">studies IT</a></h1>
         <nav>
            <ul>
            <% if player_signed_in? %>
              <li>
                <%= link_to "マイページ", edit_user_player_path(current_player.id), class: 'user-header' %>
              </li>
              <li>
                <%= link_to "ランキング", user_players_path, class: 'user-header' %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_player_session_path, method: :delete, class: 'user-header' %>
              </li>
            <% elsif admin_signed_in? %>
              <li>
                <%= link_to "クイズ作成", new_admin_quiz_path, class: 'admin-header' %>
              </li>
              <li>
                <%= link_to "クイズ一覧", admin_quizzes_path, class: 'admin-header' %>
              </li>
              <li>
                <%= link_to "ユーザー一覧", admin_players_path, class: 'admin-header' %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'admin-header' %>
              </li>
            <% else %>
              <li>
                <%= link_to "新規登録", new_player_registration_path, class: 'user-header' %>
              </li>
              <li>
                <%= link_to "ログイン", new_player_session_path, class: 'user-header' %>
              </li>
            <% end %>
            </ul>
         </nav>
  </header>
    <%= yield %>
    <footer>
      <div>
        <p>© 2022 studiesIT inc.</p>
      </div>
    </footer>
  </body>
</html>